### ISSUE TITLE
How can I print mutation without mutation_filtering?

### ISSUE THREAD

**Issue by yacai0412** [evronylab/HiDEF-seq#1]
Hi,
I just want to print the raw single molecule mutation without your in-build mutation filter, since some of the filers are not well suited for our data. How can I print all the raw mutation file from RDS file just after bamfilezmw_all.R?

Many thanks

**Comment by gevro** [comment]
Unfortunately I don't have code to do that. But you could filter for calls in the 'fwd' part of the dataframe that are not in the 'rev' part, and vice versa. See also the bamfilezmw_all.R code for details of the data structure.

**Comment by yacai0412** [comment]
Thank you for your feedback, and I still have a question that is there a calling set for fwd/rev/zmw mutations in the RDS output by make_bamfilezmw_all.R? and how can I save a calling set in a txt format file?
many thanks!

**Comment by gevro** [comment]
The output of make_bamfilezmw_all.R has fwd for all fwd read information, and rev for all rev read information. ZMW joins them for positions where the base change was found both in fwd and rev. You need to write your own code if you want to extract from this upstream stage ssDNA changes (found in fwd but not rev, and vice versa) and/or dsDNA changes (found in zmw). You can use standard output functions of R to output to txt format.

**Comment by yacai0412** [comment]
> 

thank you very much!
I'll try it soon
