### ISSUE TITLE
Nrefbed and gnomad_sensitivity_ref files

### ISSUE THREAD

**Issue by scottrk** [evronylab/HiDEF-seq#2]
I'm looking to implement this pipeline, but it is unclear how the `chm13.draft_v1.0.N.merged.bed` and `af.only.0.001.gnomad.v3.1.2.CHM13_v1.bw` files were generated or where they can be obtained. Do you have any instructions for that or are able to share?

**Comment by gevro** [comment]
Hi, We bundled these and other smaller reference files inside the docker in the location /hidef/references_CHM13v1/
Hope this helps!

**Comment by scottrk** [comment]
Got it!. Thanks.
